CREATE TABLE IF NOT EXISTS public.aspects (
  aspect_id text PRIMARY KEY,
  aspect_name text NOT NULL,
  owner_question text NOT NULL DEFAULT '',
  family_codes text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.aspects TO authenticated;
GRANT ALL ON public.aspects TO service_role;
ALTER TABLE public.aspects ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS aspects_read ON public.aspects;
CREATE POLICY aspects_read ON public.aspects FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS aspects_admin_write ON public.aspects;
CREATE POLICY aspects_admin_write ON public.aspects FOR ALL TO authenticated USING (private.has_role(auth.uid(),'admin'::app_role)) WITH CHECK (private.has_role(auth.uid(),'admin'::app_role));

ALTER TABLE public.control_register ADD COLUMN IF NOT EXISTS aspect_id text;

CREATE TABLE IF NOT EXISTS public.stage_exit_criteria (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  criterion_id text NOT NULL UNIQUE,
  stage_number int NOT NULL,
  stage_name text NOT NULL DEFAULT '',
  exit_criterion text NOT NULL,
  evidence_required text NOT NULL DEFAULT '',
  blocking text NOT NULL DEFAULT 'HARD',
  linked_families text NOT NULL DEFAULT '',
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.stage_exit_criteria TO authenticated;
GRANT ALL ON public.stage_exit_criteria TO service_role;
ALTER TABLE public.stage_exit_criteria ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS sec_read ON public.stage_exit_criteria;
CREATE POLICY sec_read ON public.stage_exit_criteria FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS sec_admin_write ON public.stage_exit_criteria;
CREATE POLICY sec_admin_write ON public.stage_exit_criteria FOR ALL TO authenticated USING (private.has_role(auth.uid(),'admin'::app_role)) WITH CHECK (private.has_role(auth.uid(),'admin'::app_role));

CREATE TABLE IF NOT EXISTS public.aspect_weight_overrides (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stage_number int NOT NULL,
  aspect_id text NOT NULL,
  weight numeric NOT NULL,
  version int NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (stage_number, aspect_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.aspect_weight_overrides TO authenticated;
GRANT ALL ON public.aspect_weight_overrides TO service_role;
ALTER TABLE public.aspect_weight_overrides ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS awo_read ON public.aspect_weight_overrides;
CREATE POLICY awo_read ON public.aspect_weight_overrides FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS awo_admin_write ON public.aspect_weight_overrides;
CREATE POLICY awo_admin_write ON public.aspect_weight_overrides FOR ALL TO authenticated USING (private.has_role(auth.uid(),'admin'::app_role)) WITH CHECK (private.has_role(auth.uid(),'admin'::app_role));

ALTER TABLE public.escalation_rules ADD COLUMN IF NOT EXISTS rule_id text;
ALTER TABLE public.escalation_rules ADD COLUMN IF NOT EXISTS aspect_id text;
ALTER TABLE public.escalation_rules ADD COLUMN IF NOT EXISTS conditions text NOT NULL DEFAULT '';
ALTER TABLE public.escalation_rules ADD COLUMN IF NOT EXISTS severity_floor text NOT NULL DEFAULT 'YELLOW';
ALTER TABLE public.escalation_rules ADD COLUMN IF NOT EXISTS action text NOT NULL DEFAULT '';
ALTER TABLE public.escalation_rules ADD COLUMN IF NOT EXISTS false_positive_checks text NOT NULL DEFAULT '';
ALTER TABLE public.escalation_rules ADD COLUMN IF NOT EXISTS stages int[] NOT NULL DEFAULT '{}';
UPDATE public.escalation_rules SET rule_id = 'LEGACY-' || left(id::text,8) WHERE rule_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS escalation_rules_rule_id_key ON public.escalation_rules (rule_id);
INSERT INTO public.aspects (aspect_id,aspect_name,owner_question,family_codes) VALUES
('A01','Entitlement & Development Rights','Will we get the approval, and will it survive?','ACQ-ZON; ACQ-REG; ACQ-TTL; ENT-PTH; ENT-ADM; ENT-HRG; ENT-CMP; ENT-RES; PAV-CND; PAV-CHL; SLS-REG'),
('A02','Permits, Inspections & Agency Clearance','Will the paper be in hand when we need it, and are we clear with the inspectors?','ENT-ENV; ENT-FNL; DES-COD; DES-PMT; PRE-PER; PRE-NTP; CON-AGY; CLO-INS; CLO-VIO'),
('A03','Site, Ground & Environmental Conditions','What is this piece of ground going to hit us with that nobody priced?','ACQ-GEO; ACQ-ENV; ACQ-HYD; ACQ-BLD; ACQ-SRV; ENT-STM; PRE-TMP; CON-ENC'),
('A04','Utilities, Access & Offsite Infrastructure','Will there be power, water, sewer and a legal way in when we need them?','ACQ-UTL; ACQ-ACC; ENT-UTL; ENT-TRF; DES-UTL; CON-UTL'),
('A05','Program Integrity & Owner Decision Control','Are we still building what we underwrote, and are we the ones holding it up?','DES-BAS; DES-OWN; DES-ARC; ENT-ARC; ENT-LND; PRE-ASM; CON-OWN'),
('A06','Design Coordination & Documentation','Are the drawings finished, do they fit together, and can they be built?','DES-STR; DES-MEP; DES-ELE; DES-ENC; DES-CIV; DES-CRD; DES-SPC; ENT-CIV; PRE-DES; PRE-BIM; CON-RFI'),
('A07','Contract Structure, Scope & Counterparty Capability','Is the team real, and does the contract put the risk where we think it is?','ACQ-OWN; ACQ-TEAM; PRE-DEL; PRE-BIF; PRE-CON; PRE-SCP; PRE-SEL; PRE-SUB; CON-SUB; CON-FLD'),
('A08','Cost Position & Contingency','What will this cost when it is done, and how much room is left?','DES-CST; PRE-CST; PRE-EST; PRE-CTG; CON-CST; CON-CHG'),
('A09','Procurement, Buyout & Long Lead','Is it bought, is the price locked, and will it show up on time?','DES-LLD; PRE-AWD; PRE-BUY; PRE-PRC; PRE-LBR; CON-PRC'),
('A10','Schedule Integrity & Critical Path','When does this open, and does the schedule still match the field?','ACQ-SCH; DES-SCH; PRE-SCH; CON-SCH; CLO-TRN'),
('A11','Capital Structure & Sponsor Solvency','Does the money to finish and exit exist, and is it still committed?','ACQ-FIN; FIN-CAP; FIN-EQY; FIN-COV; PAV-RUN; SLS-INV; SLS-TKO'),
('A12','Payment, Draw & Cash Movement','Is every dollar leaving the account actually in the ground?','FIN-DRW; PRE-PAY; CON-PAY; CLO-FIN; SLS-DEP'),
('A13','Quality, Commissioning & Handover','Is the work any good, and can we actually accept it?','PRE-QA; CON-QAL; CLO-CX; CLO-PCH; CLO-DOC; CLO-OPS'),
('A14','Safety, Insurance & Dispute Exposure','If this goes wrong, who pays — and is somebody building a case?','ACQ-INS; PRE-INS; CON-SAF; CON-COR; CLO-RSK'),
('A15','Demand, Revenue & Absorption','Will it sell or lease at our number?','PAV-ANC; SLS-VEL; SLS-PRC; SLS-CLS; SLS-OPS')
ON CONFLICT (aspect_id) DO UPDATE SET aspect_name=EXCLUDED.aspect_name, owner_question=EXCLUDED.owner_question, family_codes=EXCLUDED.family_codes;

UPDATE public.control_register cr SET aspect_id = m.aspect_id
FROM (SELECT a.aspect_id, btrim(f) AS family_code FROM public.aspects a, unnest(string_to_array(a.family_codes,';')) f) m
WHERE btrim(cr.family_code) = m.family_code AND cr.aspect_id IS DISTINCT FROM m.aspect_id;

INSERT INTO public.stage_exit_criteria (stage_number,stage_name,criterion_id,exit_criterion,evidence_required,blocking,linked_families) VALUES
(1,'Acquisition Due Diligence','ACQ-EX-101','Site control is documented and every diligence deadline, extension right and termination right is calendared','Executed PSA or option with amendments; dated deadline register','HARD','ACQ-OWN, ACQ-TTL'),
(1,'Acquisition Due Diligence','ACQ-EX-102','Every physical condition that can change the price has been investigated, not assumed — soils, contamination, water, existing structures','Geotechnical report; Phase I and any Phase II; survey; structural assessment','HARD','ACQ-GEO, ACQ-ENV, ACQ-HYD, ACQ-BLD, ACQ-SRV'),
(1,'Acquisition Due Diligence','ACQ-EX-103','Utility capacity and legal access are confirmed in writing by the controlling authority, not inferred from adjacency','Will-serve or capacity letters; recorded access instrument or curb-cut confirmation','HARD','ACQ-UTL, ACQ-ACC'),
(1,'Acquisition Due Diligence','ACQ-EX-104','The entitlement path, its decision body, and a realistic duration are documented and carried in the schedule','Jurisdiction matrix; pre-application record; risk-adjusted schedule','HARD','ACQ-REG, ACQ-ZON, ACQ-SCH'),
(1,'Acquisition Due Diligence','ACQ-EX-105','Carry cost, tax basis, incentives and total capital need are modelled against the entitlement duration actually documented','Underwriting model; carry schedule; incentive documentation','HARD','ACQ-FIN'),
(1,'Acquisition Due Diligence','ACQ-EX-106','Every unverified assumption carried into acquisition is recorded with an owner, a resolution date, and the decision it exposes','Assumption register','HARD','ACQ-TEAM, ACQ-SCH'),
(1,'Acquisition Due Diligence','ACQ-EX-107','Insurance history, claims history and risk transfer position are reviewed for the site and the transaction','Loss runs; policy review memorandum','SOFT','ACQ-INS'),
(2,'Site Plan and Entitlement Approval','ENT-EX-201','The approving resolution is adopted, memorialised in writing, and every condition is extracted into a dated register with a named owner','Adopted resolution; conditions matrix','HARD','ENT-RES, PAV-CND'),
(2,'Site Plan and Entitlement Approval','ENT-EX-202','Every approval expiration, vesting period and extension right is calendared with the trigger that starts each clock','Entitlement register with expiration dates','HARD','PAV-CND, ENT-RES'),
(2,'Site Plan and Entitlement Approval','ENT-EX-203','The statutory challenge window is identified and no irreversible spend is committed inside it without a bound indemnity or title endorsement','Counsel memorandum; challenge-window calendar','HARD','PAV-CHL'),
(2,'Site Plan and Entitlement Approval','ENT-EX-204','All outside-agency and environmental permits on the critical path are identified with agency, duration and dependency','Agency matrix; submission log','HARD','ENT-ENV, ENT-FNL'),
(2,'Site Plan and Entitlement Approval','ENT-EX-205','Approved civil, architectural and landscape basis is released into design development with change control, so approved conditions are not silently dropped','Design basis memorandum; change control log','HARD','ENT-CIV, ENT-ARC, ENT-LND'),
(2,'Site Plan and Entitlement Approval','ENT-EX-206','Utility and traffic commitments made during approval are reconciled against the design and carried in budget and schedule','Utility correspondence; traffic mitigation commitments','HARD','ENT-UTL, ENT-TRF'),
(2,'Site Plan and Entitlement Approval','ENT-EX-207','Stormwater and drainage approvals reflect the design actually being permitted, not the concept that was heard','Approved stormwater package','SOFT','ENT-STM'),
(3,'Design Development and Construction Documents','DES-EX-301','The written design basis is frozen and the current design is reconciled against the underwriting program and area schedule','Design basis document; area tabulation versus pro forma','HARD','DES-BAS'),
(3,'Design Development and Construction Documents','DES-EX-302','Every discipline has issued a complete set against a defined deliverable standard, with sheets listed but not issued identified','Discipline drawing lists; issued sets','HARD','DES-ARC, DES-STR, DES-MEP, DES-ELE, DES-CIV, DES-ENC'),
(3,'Design Development and Construction Documents','DES-EX-303','Interdisciplinary coordination is complete and unresolved clashes are enumerated rather than assumed closed','Coordination or BIM clash report with resolution status','HARD','DES-CRD'),
(3,'Design Development and Construction Documents','DES-EX-304','Code, life safety and accessibility analysis is complete against the stated governing code version','Code analysis; life safety plans','HARD','DES-COD'),
(3,'Design Development and Construction Documents','DES-EX-305','Utility capacity is confirmed against final design demand and the energization path has named dates','Utility capacity confirmation; energization plan','HARD','DES-UTL'),
(3,'Design Development and Construction Documents','DES-EX-306','Long-lead items are identified with order-by dates that are on the schedule, not on a list','Long-lead register with release dates','HARD','DES-LLD, DES-SCH'),
(3,'Design Development and Construction Documents','DES-EX-307','Current design cost is reconciled to the budget with value engineering decisions recorded and their scope consequences accepted','Reconciled estimate; VE log','HARD','DES-CST'),
(3,'Design Development and Construction Documents','DES-EX-308','Owner decisions required for permit and bid are closed, and any that remain open have a default position and a date','Owner decision log','HARD','DES-OWN'),
(3,'Design Development and Construction Documents','DES-EX-309','The permit set is complete and the filing path, reviewer and expected duration are documented','Permit set; filing plan','HARD','DES-PMT'),
(4,'Preconstruction GMP and Buyout','PRE-EX-401','Delivery model is classified and the executed contract form matches it, with risk allocation, notice provisions and time bars documented','Executed agreement; project execution plan','HARD','PRE-DEL, PRE-BIF, PRE-CON'),
(4,'Preconstruction GMP and Buyout','PRE-EX-402','Every early-release package has a gate record, a canonical issue set and a written owner acceptance of its residual incompleteness','Package register; release gate records','HARD','PRE-BIF, PRE-ASM'),
(4,'Preconstruction GMP and Buyout','PRE-EX-403','No open assumption with HIGH or VERY_HIGH irreversibility remains past its latest responsible moment without a recorded owner acceptance','Assumption register with irreversibility and LRM','HARD','PRE-ASM'),
(4,'Preconstruction GMP and Buyout','PRE-EX-404','The scope interface matrix shows no unassigned gap and no undefined overlap on any material trade boundary','Scope matrix with assignment status','HARD','PRE-SCP'),
(4,'Preconstruction GMP and Buyout','PRE-EX-405','GMP is supported by a priced, dated document list incorporated by reference and reconciled to an independent estimate at trade level','GMP exhibit; independent estimate reconciliation','HARD','PRE-CST, PRE-EST'),
(4,'Preconstruction GMP and Buyout','PRE-EX-406','Contingency structure, drawdown authority and reporting cadence are defined before the first dollar is drawn','Contract contingency provisions; drawdown procedure','HARD','PRE-CTG'),
(4,'Preconstruction GMP and Buyout','PRE-EX-407','Long-lead and critical-path scopes are awarded or released against schedule need dates with confirmed delivery commitments','Procurement log; purchase orders with delivery dates','HARD','PRE-AWD, PRE-PRC'),
(4,'Preconstruction GMP and Buyout','PRE-EX-408','Required insurance, endorsements and bonds are in force with the endorsement forms on file, not certificates alone','Endorsements; bonds; certificate register','HARD','PRE-INS'),
(4,'Preconstruction GMP and Buyout','PRE-EX-409','Baseline schedule is accepted, logic-validated, and its durations tested against real permit, utility and fabrication times','Accepted baseline; logic validation report','HARD','PRE-SCH'),
(4,'Preconstruction GMP and Buyout','PRE-EX-410','Notice to proceed conditions precedent are satisfied and evidenced, including loan closing and funding availability','NTP checklist with evidence; loan closing confirmation','HARD','PRE-NTP'),
(4,'Preconstruction GMP and Buyout','PRE-EX-411','Contractor and material subcontractors are qualified on capacity, financial health and comparable experience','Qualification review; financial review','HARD','PRE-SEL, PRE-SUB'),
(4,'Preconstruction GMP and Buyout','PRE-EX-412','Payment procedure, schedule of values, lien waiver regime and retainage terms are agreed before the first requisition','Executed payment procedure; approved SOV','HARD','PRE-PAY'),
(5,'Construction','CON-EX-501','Substantial completion is achieved against the contract definition, not against a percentage','Certificate of substantial completion','HARD','CON-SCH'),
(5,'Construction','CON-EX-502','Cost at completion is forecast from actual commitments and open change exposure, with contingency remaining stated','Anticipated cost report','HARD','CON-CST, CON-CHG'),
(5,'Construction','CON-EX-503','No open change event or claim notice remains unpriced or unanswered past its contractual reply period','Change log; correspondence log with response dates','HARD','CON-CHG, CON-COR'),
(5,'Construction','CON-EX-504','All permanent utilities are energized or have a confirmed energization date inside the closeout window','Utility energization confirmations','HARD','CON-UTL'),
(5,'Construction','CON-EX-505','Open agency violations that block a certificate are cleared or have a written clearance path with dates','Violation register with clearance status','HARD','CON-AGY'),
(5,'Construction','CON-EX-506','Required inspections and testing are complete with results accepted by the authority and the engineer of record','Inspection and test reports','HARD','CON-QAL'),
(5,'Construction','CON-EX-507','Field production has been independently verified against billing for the final period','Field verification report versus pay application','HARD','CON-FLD, CON-PAY'),
(5,'Construction','CON-EX-508','Every unresolved Stage 4 assumption and control carried forward is either closed with evidence or explicitly re-accepted','Continuity register','HARD','CON-OWN'),
(6,'Closeout TCO and Certificate of Occupancy','CLO-EX-601','The certificate of occupancy or temporary certificate is issued for the scope claimed, with its conditions and expiry recorded','Issued TCO or CO with conditions','HARD','CLO-INS, CLO-VIO'),
(6,'Closeout TCO and Certificate of Occupancy','CLO-EX-602','Every agency clearance required for the certificate has a named owner and a documented sign-off','Agency clearance register with sign-offs','HARD','CLO-INS'),
(6,'Closeout TCO and Certificate of Occupancy','CLO-EX-603','All systems required for occupancy have completed functional performance testing and been accepted','Commissioning report; functional test records','HARD','CLO-CX'),
(6,'Closeout TCO and Certificate of Occupancy','CLO-EX-604','Punch list is enumerated, valued, and secured by retention or escrow at not less than the valued open scope','Punch list with values; retention calculation','HARD','CLO-PCH'),
(6,'Closeout TCO and Certificate of Occupancy','CLO-EX-605','As-builts, O and M manuals, warranties and training are delivered, with warranty commencement fixed in writing per system','Closeout document index; warranty commencement schedule','HARD','CLO-DOC'),
(6,'Closeout TCO and Certificate of Occupancy','CLO-EX-606','Final payment, lien releases and financial closeout are complete or the remaining exposure is quantified and secured','Final lien releases; financial closeout statement','HARD','CLO-FIN'),
(6,'Closeout TCO and Certificate of Occupancy','CLO-EX-607','Insurance transitions from builders risk to permanent property coverage with no gap in dates or scope','Bound permanent policy; builders risk expiry','HARD','CLO-RSK'),
(6,'Closeout TCO and Certificate of Occupancy','CLO-EX-608','Operations handover is complete — staffing, service contracts, systems access and turnover phasing','Operations handover record','HARD','CLO-OPS, CLO-TRN'),
(7,'Sales Lease-Up Stabilization and Takeout','SLS-EX-701','Offering plan, disclosure and regulatory obligations are current and consistent with what is actually being delivered','Current offering plan and amendments','HARD','SLS-REG'),
(7,'Sales Lease-Up Stabilization and Takeout','SLS-EX-702','Absorption has reached the underwritten threshold required by the takeout facility, measured against the original curve','Absorption report versus underwriting','HARD','SLS-VEL'),
(7,'Sales Lease-Up Stabilization and Takeout','SLS-EX-703','Achieved pricing net of concessions supports the underwritten value and the exit assumption','Net effective pricing analysis','HARD','SLS-PRC'),
(7,'Sales Lease-Up Stabilization and Takeout','SLS-EX-704','Deposits and escrows are intact, and cancellation and fallout rates are within the modelled range','Escrow reconciliation; contract fallout report','HARD','SLS-DEP'),
(7,'Sales Lease-Up Stabilization and Takeout','SLS-EX-705','Closings are converting, and anything blocking revenue commencement is enumerated with an owner','Closing pipeline with blockers','HARD','SLS-CLS'),
(7,'Sales Lease-Up Stabilization and Takeout','SLS-EX-706','Stabilized NOI and occupancy meet the debt yield and coverage tests in the takeout commitment','Stabilized operating statement; covenant calculation','HARD','SLS-OPS'),
(7,'Sales Lease-Up Stabilization and Takeout','SLS-EX-707','Every takeout condition precedent is satisfied and evidenced before the construction facility matures','Takeout condition checklist with evidence','HARD','SLS-TKO'),
(7,'Sales Lease-Up Stabilization and Takeout','SLS-EX-708','Investor and partnership obligations — distributions, promote, reporting, consents — are current','Partnership compliance record','HARD','SLS-INV')
ON CONFLICT (criterion_id) DO UPDATE SET stage_number=EXCLUDED.stage_number, stage_name=EXCLUDED.stage_name, exit_criterion=EXCLUDED.exit_criterion, evidence_required=EXCLUDED.evidence_required, blocking=EXCLUDED.blocking, linked_families=EXCLUDED.linked_families;

INSERT INTO public.escalation_rules (rule_id,aspect_id,name,description,conditions,severity_floor,action,false_positive_checks,stages,scope,severity,condition) SELECT v.rule_id,v.aspect_id,v.name,v.description,v.conditions,v.severity_floor,v.action,v.fpc,v.stages,'control',v.severity_floor,'{}'::jsonb FROM (VALUES
('CZ-RULE-PRE-001','A07','Uncontrolled early release','Detect field release without explicit package governance.','package.release_status == ''RELEASED'' AND package.gate_status is null OR package.canonical_issue is null','RED','Stop further irreversible work until package gate/evidence is established or owner accepts risk.','Emergency stabilization work; Authority-mandated immediate work','{4}'::int[]),
('CZ-RULE-PRE-002','A05','High-irreversibility assumption nearing latest responsible moment','Escalate controlled incompleteness before it becomes rework.','assumption.status in [''CONTROLLED_ASSUMPTION'',''IN_PROGRESS''] AND assumption.irreversibility in [''HIGH'',''VERY_HIGH''] AND days_to_latest_responsible_moment <= 7','YELLOW','Resolve, redesign release sequence, or obtain owner accepted-risk decision.','Field work intentionally deferred beyond package date','{4}'::int[]),
('CZ-RULE-PRE-003','A07','Unassigned trade interface','Find physical/contractual work nobody owns.','interface.assignment_count == 0 AND interface.materiality != ''LOW''','YELLOW','Assign responsibility before affected award/release.','Scope intentionally owner-performed and documented','{4}'::int[]),
('CZ-RULE-PRE-004','A07','Duplicate trade assignment','Find overlap likely to create bid distortion/dispute.','interface.assignment_count > 1 AND interface.boundary_defined == false','YELLOW','Clarify boundary and reconcile duplicate pricing before award.','Intentional shared responsibility with explicit split','{4}'::int[]),
('CZ-RULE-PRE-005','A08','Unsupported forecast revision pattern','Flag repeated cost movement without auditable basis.','cost_item.revision_count >= 2 AND abs(cost_item.current - cost_item.prior) >= materiality AND cost_item.scope_basis_complete == false','YELLOW','Require scope/quantity/rate/ancillary-cost reconciliation and reviewer approval.','Documented market escalation; Approved design scope change','{4}'::int[]),
('CZ-RULE-PRE-006','A08','Apparent buyout saving from shifted scope','Prevent false savings.','award.variance_to_budget < -materiality AND scope.shifted_to_adjacent_trade == true OR owner_direct_cost_added == true','YELLOW','Restate true net buyout variance after scope migration.','Approved value engineering with verified scope deletion','{4}'::int[]),
('CZ-RULE-PRE-007','A09','Procurement schedule mathematically impossible','Surface late approval/fabrication before installation slips.','item.forecast_delivery_date > item.latest_delivery_date','RED if critical_path else YELLOW','Recovery plan: accelerate review/fabrication, alternate source, resequence, or revise milestone.','Installation resequenced with verified float','{4}'::int[]),
('CZ-RULE-PRE-008','A06','Released work threatened by later design revision','Link revisions to already-committed work.','revision.date > package.release_date AND revision.affects_released_scope == true AND package.irreversible_progress > 0','YELLOW','Immediate released-work impact review; quantify rework/cost/schedule before field continuation.','Revision is administrative/no physical effect','{4}'::int[]),
('CZ-RULE-PRE-009','A02','Construction need precedes permit readiness','Prevent schedule fantasy.','permit.need_date <= today + 30d AND permit.status not in [''APPROVED'',''ISSUED''] AND permit.affects_critical_or_near_critical == true','YELLOW','Escalate objections/prerequisites and model milestone impact.','Work may lawfully proceed under separate permit/package','{4}'::int[]),
('CZ-RULE-PRE-010','A06','Critical clash aging into fabrication/pour window','Escalate high-consequence coordination backlog.','clash.criticality in [''HIGH'',''CRITICAL''] AND clash.status == ''OPEN'' AND days_to_need_date <= 14','RED','Mandatory coordination closure/release decision.','Affected work formally deferred','{4}'::int[]),
('CZ-RULE-PRE-011','A07','Critical control has no contractual owner','Prevent accountability vacuum.','control.criticality == ''CRITICAL'' AND control.contractual_owner is null','RED','Resolve responsibility through contract/amendment/delegation before release.','Owner intentionally self-performs and records acceptance','{4}'::int[]),
('CZ-RULE-PRE-012','A13','Required inspection not procured before work','Avoid work proceeding without acceptance pathway.','inspection.required == true AND inspection.assigned_party is null OR inspection.contract_status != ''READY'' AND days_to_work <= 7','RED','Procure/confirm inspection and hold-point protocol before work.','Authority confirms inspection not required','{4}'::int[]),
('CZ-RULE-PRE-013','A07','Exclusion has no receiving trade','Classic scope-gap detector.','scope_item.type == ''EXCLUSION'' AND scope_item.receiving_party is null','YELLOW','Assign and price excluded work before award.','Excluded from entire project by approved owner decision','{4}'::int[]),
('CZ-RULE-PRE-014','A09','Critical trade award with unresolved clarifications','Prevent premature award.','trade.criticality == ''CRITICAL'' AND award.status in [''RECOMMENDED'',''READY''] AND open_material_clarifications > 0','YELLOW','Close clarifications or explicitly carry controlled exceptions in award.','Clarification has no cost/schedule/scope effect','{4}'::int[]),
('CZ-RULE-PRE-015','A08','Fast-track contingency insufficient for unresolved design exposure','Make intentional incompleteness financial.','delivery_model in [''FAST_TRACK'',''HYBRID''] AND high_irreversibility_open_assumptions > 0 AND early_release_interface_contingency <= 0','YELLOW','Quantify interface/design-development exposure and establish reserve or resolve assumptions.','All exposure contractually transferred and verified','{4}'::int[]),
('CZ-RULE-PRE-016','A03','Material logistics cost absent from award basis','Find ancillary-cost holes.','trade.requires_rigging_or_hoisting == true AND trade.ancillary_cost_complete == false','YELLOW','Reconcile rigging/hoisting/freight/permits before award.','Cost explicitly carried in CM general conditions or another trade','{4}'::int[]),
('CZ-RULE-PRE-017','A06','Global design percent masks near-term package deficiency','Prioritize the work about to be built.','project.design_pct >= 80 AND next_critical_package.readiness_pct < 70','YELLOW','Report package-level deficiency instead of global design percent.','Package intentionally deferred beyond critical window','{4}'::int[]),
('CZ-RULE-PRE-018','A05','Phase 4 issue lost at Phase 5 transition','Project memory invariant.','phase == 5 AND count(open_phase4_inheritable) > count(active_phase5_inherited_watches)','RED','Restore inherited controls before automated Phase 5 scoring.','Item was verified/resolved/superseded before transition','{4}'::int[]),
('CZ-RULE-ENT-001','A01','Approval condition expiring during project stall','Approval granted with conditions and the clock kept running after activity stopped.','approval.status == ''GRANTED'' AND condition.satisfied == false AND condition.expiration_date - today <= 90 AND project.days_since_last_entitlement_activity >= 60','RED','File the written extension or tolling request with the approving body before the expiration date and record the new expiration; if no extension exists, fund and start the condition sequence this month.','Condition satisfied in fact and only evidence upload outstanding; Approval tolled by statute or emergency order with written agency confirmation','{1,2,7}'::int[]),
('CZ-RULE-ENT-002','A01','Irreversible spend inside the statutory challenge window','Money going into the ground before the appeal period on the approval has run.','approval.status == ''GRANTED'' AND today - approval.grant_date <= approval.statutory_challenge_period_days AND commitment.irreversible_spend_since_grant >= materiality','RED','Publish the challenge run-out date to the capital committee and hold irreversible spend until it passes or a zoning and land use title endorsement or challenge indemnity is bound.','Spend fully refundable under the vendor agreement; Challenge period already expired on the controlling approval','{1,2,7}'::int[]),
('CZ-RULE-ENT-003','A01','Third party suit against the approving jurisdiction','A neighbor or interest group is attacking the approval and the owner is not at the table.','litigation.filed_date >= approval.grant_date AND litigation.relief_sought includes ''VACATE_APPROVAL'' AND project.intervention_status != ''PARTY_OF_RECORD''','RED','Direct counsel to intervene as a party of record before the intervention deadline and obtain a written litigation timeline; re-baseline closing and start dates against it.','Suit challenges a different approval heard on the same agenda; Suit dismissed with prejudice and appeal period run','{1,2,7}'::int[]),
('CZ-RULE-ENT-004','A01','Private restriction survives the public approval','Zoning says yes and the recorded title documents say no.','zoning.approval_status == ''GRANTED'' AND restriction.conflicts_with_program == true AND restriction.release_status != ''RECORDED''','RED','Obtain a recorded release or estoppel from every benefited party or reduce the program to comply, before land closing or notice to proceed.','Restriction expired by its terms with affirmative title coverage issued; Restriction superseded by a later recorded declaration','{1,2,7}'::int[]),
('CZ-RULE-PMT-001','A02','Occupancy blocked by an agency sign-off nobody owns','The certificate is not gated by the building department alone and one clearance has no name against it.','milestone.type in [''TCO'',''CO''] AND days_to_milestone <= 60 AND count(agency_signoff where responsible_party is null OR submission_date is null) > 0','RED','Assign one named accountable party and a submission date to every outstanding occupancy clearance and obtain each agency''s current queue time in writing this week.','Agency confirms in writing the clearance is a final CO precondition only; Clearance not applicable to this occupancy type per the agency checklist','{2,5,6}'::int[]),
('CZ-RULE-PMT-002','A02','Deferred submittal unapproved as its work approaches','Permit issued does not mean permit complete.','permit.status == ''ISSUED'' AND deferred_submittal.approval_status != ''APPROVED'' AND deferred_submittal.related_work_start_date - today <= 30','RED if deferred_submittal.affects_life_safety else YELLOW','Confirm the reviewer queue time and either move the related work behind it or obtain the jurisdiction''s written install-at-risk position naming who carries removal cost.','Deferred package covers work under a separate later phase permit; Jurisdiction reviews at inspection rather than plan review','{3,4,5}'::int[]),
('CZ-RULE-PMT-003','A02','Repeat inspection failure or open blocking violation','The same item keeps being rejected or a violation stands between the project and its certificate.','inspection.failure_count_same_item >= 2 AND inspection.reinspection_date is null OR violation.status == ''OPEN'' AND violation.blocks_certificate == true','RED','Take a written corrective plan signed by the trade and the engineer of record to the building official, request a pre-inspection walk, and hold that scope''s payment until it passes.','Failure was administrative with no work rejected; Violation issued against an adjacent parcel','{4,5,6}'::int[]),
('CZ-RULE-PMT-004','A02','Permit lapsing from inactivity','Suspended work quietly kills the permit and re-issue lands under current code.','permit.status == ''ISSUED'' AND today - permit.last_inspection_date >= permit.inactivity_expiration_days - 45 AND project.field_activity_status in [''SUSPENDED'',''IDLE'']','RED','Schedule a qualifying inspection or file the written extension before the lapse date; price the code delta a re-issue would trigger so the cost of drifting is visible.','No inactivity expiration for this permit class in the adopted code; Extension already granted and the register is stale','{4,5}'::int[]),
('CZ-RULE-GND-001','A03','Foundation designed on assumed ground','Bearing capacity is a design assumption until borings say otherwise.','foundation.design_basis == ''ASSUMED_BEARING'' OR geotech.boring_count < geotech.required_boring_count OR today - geotech.report_date >= 730 AND excavation.start_date - today <= 60','RED if foundation.type in [''DEEP'',''MAT''] else YELLOW','Commission supplemental borings on the actual footprint before the foundation package is released and require the geotechnical engineer to state design bearing and groundwater elevation in writing.','Adjacent identical structure has verified as-built founding conditions accepted by the geotech of record; Code presumptive bearing accepted by the building official','{1,2,4}'::int[]),
('CZ-RULE-GND-002','A03','Environmental obligation open against a closing or vertical start','Contamination not closed out by the regulator is still the owner''s.','environmental.rec_count > 0 AND environmental.phase2_status != ''COMPLETE'' AND land.closing_date - today <= 45 OR remediation.status == ''IN_PROGRESS'' AND regulatory_closure.nfa_status != ''ISSUED'' AND vertical_construction.start_date - today <= 30','RED','Obtain the no further action letter or a recorded engineering control with a written O and M obligation and cost, and bind environmental liability coverage sized to remaining exposure before closing or vertical start.','Phase II scoped for de minimis historical use with written agency concurrence; Closure by an approved in-place control already recorded','{1,2,4,5}'::int[]),
('CZ-RULE-GND-003','A03','Subsurface allowance burning ahead of the earthwork','Differing site conditions are consuming the allowance faster than the work is completing.','unforeseen_condition.count >= 2 AND site_allowance.consumed_pct >= 60 AND earthwork.complete_pct <= 50 OR dewatering.actual_flow_gpm > dewatering.design_flow_gpm * 1.5','RED if site_allowance.consumed_pct >= 80 else YELLOW','Re-forecast remaining subsurface exposure from actual encountered unit rates, reset the allowance to that number, and fund the delta from contingency with written IC acknowledgement rather than absorbing it silently.','Consumption driven by an approved owner scope addition; Allowance intentionally front loaded per the approved cash flow curve','{1,2,4,5}'::int[]),
('CZ-RULE-UTL-001','A04','Permanent power assumed and never contracted','Energization treated as a date on a bar chart with no utility agreement behind it.','utility.type == ''ELECTRIC'' AND schedule.energization_need_date - today <= 270 AND utility.service_agreement_status != ''EXECUTED'' OR utility.capacity_confirmation_status != ''RECEIVED''','RED','Obtain a signed service agreement with written capacity confirmation, energization date, utility equipment lead time, and any offsite upgrade cost sharing; if the utility will not commit, price temporary generation adequate to carry commissioning and occupancy.','Existing on-site service adequate and verified by a metered load letter; Utility issues agreements only inside 90 days and has confirmed capacity and queue position in writing','{1,2,3,5}'::int[]),
('CZ-RULE-UTL-002','A04','Capacity allocation conditional or expiring','A will-serve letter is a reservation with a shelf life and conditions attached.','utility.type in [''WATER'',''SEWER'',''GAS''] AND will_serve.expiration_date - today <= 120 AND will_serve.conditions_satisfied == false OR will_serve.allocated_capacity < design.peak_demand','RED','Reconcile allocated capacity against current design peak demand, satisfy or extend the letter''s conditions before expiration, and obtain written confirmation the allocation is held for this parcel and program.','Allocation renews automatically on a connection fee already paid; Design demand figure is a pre-VE number superseded by a stamped revision','{1,2,3,5}'::int[]),
('CZ-RULE-UTL-003','A04','Offsite improvement obligation unfunded or unscheduled','A condition of approval that must be built offsite before anyone can occupy.','offsite_obligation.precedes in [''BUILDING_PERMIT'',''CO'',''TCO''] AND offsite_obligation.cost_in_budget == false OR offsite_obligation.in_schedule == false','RED','Price the offsite scope from an engineered estimate, add it to budget and schedule with its own permit and agency review durations, name the performing party, and confirm in writing which milestone it actually gates.','Satisfied by a fee in lieu already paid with receipt on file; Assigned to an adjacent developer under an executed cost sharing agreement with security posted','{1,2,3,5}'::int[]),
('CZ-RULE-UTL-004','A04','Access relies on an easement that is not recorded','The design assumes a way in that the owner does not legally have.','design.relies_on_easement == true AND easement.status != ''RECORDED'' OR access.route_basis == ''ASSUMED'' AND construction.mobilization_date - today <= 90','RED','Obtain the recorded easement, crossing agreement, or curb cut permit with term, width and maintenance obligation stated, and confirm the recorded instrument number before mobilization.','Access over public right of way with an issued curb cut permit; Easement executed and submitted for recording with recorder confirmation','{1,2,3,5}'::int[]),
('CZ-RULE-PRG-001','A05','Owner decision aging past the point it drives the field','The owner is the constraint and the delay lands on the owner''s own position.','decision.status == ''PENDING_OWNER'' AND today - decision.submitted_date > decision.contractual_response_days AND decision.downstream_activity_float_days <= 5','RED if decision.on_critical_path else YELLOW','Convene a decision session with the named owner signatory, publish a default position taking effect on a stated date, and record elapsed owner time so the exposure is quantified before the contractor quantifies it.','Response clock contractually suspended for an incomplete submission; Documented strategic deferral with float purchased and acknowledged by the contractor','{2,3,4,5}'::int[]),
('CZ-RULE-PRG-002','A05','Program has drifted from what was underwritten','The building being built is no longer the building the money was raised against.','abs(program.current_gsf - program.underwritten_gsf) / program.underwritten_gsf >= 0.03 OR program.unit_mix_variance_pct >= 5 AND proforma.reunderwrite_date < program.last_change_date','RED if program.change_affects_revenue_units else YELLOW','Re-run the pro forma at the current program with current rents and costs and re-approve with the investment committee and lender before the next design release; restate the program of record so future drift is measured from truth.','Variance is a gross-to-rentable measurement restatement with no physical change; Change is an approved value-add already in a signed IC memo','{2,3,4,5}'::int[]),
('CZ-RULE-SCH-001','A10','Slip absorbed into float that does not exist','The completion date held because the network changed, not because the work recovered.','schedule_update.completion_date_change_days == 0 AND activity.total_float < 0 AND schedule_update.total_float_change < 0 AND schedule_update.logic_change_count > 0','RED','Require a variance narrative identifying every logic, duration and calendar change since the prior update and require the scheduler to restate the completion date on the prior network; withhold acceptance and payment of the update until the two dates reconcile.','Date held by an approved recovery plan with named crews, shifts and funded acceleration; Logic change corrects a documented mis-sequence confirmed in writing by the trade','{1,3,4,5}'::int[]),
('CZ-RULE-SCH-002','A10','Out of sequence progress masking the true path','Retained logic keeps a broken network reporting a healthy date.','schedule_update.out_of_sequence_activity_count / schedule_update.in_progress_activity_count >= 0.15 AND schedule_update.calculation_mode == ''RETAINED_LOGIC''','YELLOW','Direct the scheduler to rebuild logic for every out-of-sequence chain and reissue the update under progress override, and show both completion dates side by side in the monthly report.','Deliberate approved resequence already carried in a revised baseline; Early mobilization where the in-progress denominator is too small to be meaningful','{3,4,5}'::int[]),
('CZ-RULE-SCH-003','A10','Commercial delivery date unsupported by the contract schedule','A lease or opening date was promised the construction schedule cannot reach.','commercial_milestone.type in [''LEASE_DELIVERY'',''OPENING'',''CO''] AND contract_schedule.substantial_completion_date + schedule.closeout_duration_days > commercial_milestone.date - commercial_milestone.buffer_days','RED','Give the counterparty and the capital committee the true date now, quantify liquidated damage, rent abatement and termination right exposure, and either buy the recovery or renegotiate while there is still consideration to trade.','Lease has a permitted delay or force majeure extension already invoked in writing; Buffer carried in the tenant fit-out schedule and the obligation is shell only','{1,3,4,5,6}'::int[]),
('CZ-RULE-SCH-004','A10','Critical path runs through unbought work','The controlling activity has no contract, no fabricator and no one obligated to a date.','critical_path.activity.procurement_status not in [''AWARDED'',''RELEASED''] AND days_to_activity_start <= 60','RED','Award or release the controlling scope this cycle or resequence the path onto work under contract; publish the procurement date that must hold for the completion date to hold.','Owner furnished with a confirmed purchase order and delivery commitment on file; Summary placeholder scheduled to be replaced with detail at the next update','{3,4,5}'::int[]),
('CZ-RULE-SCH-005','A10','Closeout window compressed below what closeout takes','The schedule ends at substantial completion and the revenue date does not.','schedule.substantial_completion_to_turnover_days < benchmark.min_closeout_days AND commissioning.scope_status != ''COMPLETE''','RED if milestone.tco_is_revenue_trigger else YELLOW','Rebuild the closeout window from actual agency sign-off queue times, commissioning script durations, punch backlog rate and training obligations, and reissue the milestone dates from that build-up.','Turnover is phased and only the first phase needs the full window; Owner has accepted beneficial occupancy under an agreement decoupling revenue from final closeout','{4,5,6}'::int[]),
('CZ-RULE-CAP-001','A11','Fully entitled and unable to close the capital','The approvals are in hand and the money is not.','entitlement.status == ''COMPLETE'' AND capital_stack.equity_committed_pct < 100 AND today - entitlement.completion_date >= 120 OR construction_loan.commitment_status != ''EXECUTED'' AND schedule.construction_start_date - today <= 90','RED','Set a hard capital deadline tied to the earliest entitlement expiration, price the extension and carry cost of missing it, and put the fallback - recapitalization, partial sale, land sale, joint venture - in front of the sponsor before the entitlement clock runs.','Equity is discretionary capital from a committed programmatic fund with a documented call mechanic; Construction start deliberately deferred with entitlements tolled in writing','{1,4,7}'::int[]),
('CZ-RULE-CAP-002','A11','Loan covenant headroom gone','The forecast has crossed the number the loan documents actually test.','loan.covenant_headroom_pct <= 5 OR forecast.cost_at_completion > loan.approved_budget * (1 + loan.permitted_variance_pct) OR loan.balance_to_complete > loan.undrawn_commitment + equity.uncalled_commitment','RED','Take the in-balance calculation and rebalancing amount to the lender before the draw that trips it, with a signed sponsor funding commitment or lender approved reallocation; do not submit the next draw until the resolution is documented.','Overage funded by cash equity already posted to a reserve the lender accepted; Forecast includes an unapproved change not yet in the budget of record','{1,4,7}'::int[]),
('CZ-RULE-CAP-003','A11','Guarantor test failing or guarantor stretched','The completion guarantee is only as good as the balance sheet behind it.','guarantor.liquidity_test_status == ''FAIL'' OR guarantor.net_worth_test_status == ''FAIL'' OR guarantor.certificate_date < today - 365 OR guarantor.contingent_liability_project_count_change >= 2','RED','Obtain a current certified guarantor financial statement with the contingent liability schedule and either a written lender waiver or a replacement guarantor before the next draw request.','Failure is a timing artifact of a recent acquisition closing curable inside the cure period; Test run on a stale certificate','{1,4,7}'::int[]),
('CZ-RULE-CAP-004','A11','Interest reserve runs out before stabilization','The carry was modeled at a rate and a lease-up curve that are no longer true.','interest_reserve.projected_exhaustion_date < forecast.stabilization_date - 90 OR interest_reserve.balance / interest_reserve.monthly_burn < 6 OR rate.is_floating == true AND hedge.status != ''IN_PLACE''','RED','Re-run the carry at the current forward curve and current absorption forecast and either purchase the cap, fund the reserve shortfall in writing, or negotiate the extension option now while the loan is performing.','Executed and funded reserve replenishment obligation with cash posted; Reserve modeled at a strike already purchased and the hedge register is stale','{4,7}'::int[]),
('CZ-RULE-DRW-001','A12','Billing ahead of what is actually installed','The pay application is running in front of the work in the ground.','pay_app.billed_pct - field_verified_pct >= 10 AND pay_app.line_item_value >= materiality','RED','Withhold the over-billed increment on this application, require quantity-based backup for the affected lines, and have the owner''s representative certify installed quantities in the field before the next cycle is approved.','Stored or fabricated material with bill of sale, transfer of title, off-site insurance and inspection report; Lump sum general conditions or bonded item billed on time not quantity','{4,5,6,7}'::int[]),
('CZ-RULE-DRW-002','A12','Payment released without lien waiver coverage','Money leaving the account without buying down lien exposure at the lower tiers.','payment.status == ''RELEASED'' AND count(subcontractor where lien_waiver.status != ''RECEIVED'' AND contract_value >= materiality) > 0 AND lien_period.status == ''OPEN''','RED','Collect conditional waivers for the current period and unconditional for the prior period from every sub and supplier above threshold including second tier, and issue joint checks where waivers are missing before the next draw is funded.','Jurisdiction does not recognize statutory waivers and a payment bond covers the tier; Sub paid directly by the owner under an approved assignment carrying its own release','{4,5,6,7}'::int[]),
('CZ-RULE-DRW-003','A12','Retainage released before the work that justifies it','Leverage given away while punch and closeout are still open.','retainage.released_pct > 0 AND punch_list.open_items > 0 OR closeout_document.status != ''COMPLETE'' OR commissioning.acceptance_status != ''ACCEPTED''','RED if trade.criticality == ''CRITICAL'' else YELLOW','Convert the early release into a funded escrow or reduce it so retention equals at least 150 percent of the valued open punch, commissioning and closeout scope, documented by amendment not correspondence.','Contractual retainage reduction earned at a defined milestone with a maintenance bond in place; Trade scope complete and accepted with only owner filing outstanding','{5,6,7}'::int[]),
('CZ-RULE-DRW-004','A12','Draw does not match the approved budget or funding order','Reallocated lines and equity that never went in first.','draw.line_item_reallocation_pct >= 10 AND lender.written_consent_status != ''RECEIVED'' OR draw.equity_contributed_to_date < draw.required_equity_first_amount','RED','Reconcile the draw to the approved budget line by line, obtain written lender reallocation consent before submission, evidence equity-first contribution with bank records, and correct the schedule of values rather than billing against lines that no longer describe the work.','Reallocation inside a lender permitted contingency transfer right exercised by notice; Equity satisfied by a pre-closing land contribution credited at closing','{4,5,6,7}'::int[]),
('CZ-RULE-QCH-001','A13','Commissioning engaged too late to change anything','The commissioning authority arrives after the systems it is meant to review are bought.','commissioning.agent_contract_status != ''EXECUTED'' AND design.pct_complete >= 75 OR mep_equipment.procurement_status == ''AWARDED''','RED if building.systems_complexity in [''HIGH'',''CRITICAL''] else YELLOW','Engage the commissioning authority now under a written scope covering design review, submittal review, factory witness, functional performance testing and owner training, and re-open the mechanical and controls submittals it must review before installation.','Commissioning delivered by the design engineer under an executed scope covering functional testing; Utility or jurisdiction incentive program supplies the agent under a signed agreement','{4,5,6}'::int[]),
('CZ-RULE-QCH-002','A13','System required for occupancy is outside the test plan','The certificate depends on an integrated test that is not scoped or not scheduled.','system.required_for_occupancy == true AND system.in_cx_scope == false OR system.functional_test_date > milestone.tco_date - 21','RED','Put the integrated fire alarm, smoke control, emergency power and elevator acceptance tests on the schedule with agency witness dates booked now, and name the single party owning each witness test and its retest window.','System tested under a separate agency-run acceptance already scheduled; System serves a later phase outside this certificate boundary','{5,6}'::int[]),
('CZ-RULE-QCH-003','A13','Closeout record not accumulating as the work completes','Documentation, as-builts and warranty basis left to the end become the thing that holds the building.','project.pct_complete >= 75 AND closeout_document.received_pct < 25 OR as_built.update_status == ''NOT_STARTED'' OR warranty.commencement_basis is null','RED if milestone.turnover_date - today <= 60 else YELLOW','Tie the next two pay applications to a per-trade closeout submission schedule and fix the warranty commencement basis in writing for each major system so coverage does not start at substantial completion on equipment energized a year earlier.','Documents held in the contractor system and simply not transmitted; Turnover is phased and completed phases are documented','{4,5,6}'::int[]),
('CZ-RULE-SID-001','A14','Required coverage lapsed wrong or unendorsed','A certificate on file is not the same as coverage that responds.','policy.expiration_date - today <= 30 AND policy.renewal_binder_status != ''RECEIVED'' OR certificate.additional_insured_endorsement_on_file == false OR policy.limit < contract.required_limit','RED','Suspend site access for the non-compliant party and obtain the endorsement form itself naming owner and lender as additional insured on a primary and non-contributory basis with waiver of subrogation before re-entry; certificates alone do not satisfy this.','Trade covered under an owner or contractor controlled insurance program; Certificate stale but the carrier has confirmed the bound policy and endorsement in writing','{1,4,5,6}'::int[]),
('CZ-RULE-SID-002','A14','Project policy does not match the actual exposure','Insured value, term and sublimits drifted away from the job while the job grew.','builders_risk.insured_value < forecast.cost_at_completion OR builders_risk.expiration_date < schedule.substantial_completion_date + 60 OR builders_risk.soft_cost_delay_coverage == false OR builders_risk.water_damage_sublimit < materiality','RED','Increase insured value to current cost at completion, extend the term through substantial completion plus the closeout window, and test the soft cost and delay-in-start-up sublimit against actual monthly carry and lease delivery damages.','Values increase automatically under a reporting form with declared values filed; Extension already bound by endorsement and the certificate on file not reissued','{4,5,6}'::int[]),
('CZ-RULE-SID-003','A14','Somebody is building a case','A pattern of preservation letters is a claim being assembled in daylight.','count(correspondence where type in [''NOTICE_OF_DELAY'',''RESERVATION_OF_RIGHTS'',''CLAIM_PRESERVATION''] AND received_date >= today - 60) >= 3 OR contractor.notice_of_claim_status == ''FILED''','RED','Open a defended file now - preserve and freeze schedule updates, daily reports, manpower logs and the RFI and change logs for the noticed period - and answer each notice in writing inside the contractual reply period rather than in a meeting.','Standing protective letters issued monthly as contractor practice with no time or cost quantified; Notice relates to a scope already resolved by an executed change order','{4,5,6}'::int[]),
('CZ-RULE-SID-004','A14','High hazard activity or safety trend running ahead of control','Rate deterioration or an unapproved plan on the work most likely to kill someone.','safety.recordable_rate > benchmark.industry_rate * 1.5 OR high_hazard_activity.type in [''CRANE_PICK'',''EXCAVATION_OVER_5FT'',''HOT_WORK'',''CONFINED_SPACE'',''STEEL_ERECTION''] AND high_hazard_activity.plan_approval_status != ''APPROVED'' AND high_hazard_activity.start_date - today <= 7','RED','Require a stand-down and an activity specific plan signed by the performing contractor''s competent person before the activity proceeds, and test the contractor''s audit closure rate rather than its rate reporting.','Rate elevated by a single recordable on a small hour base; Plan approved and signed but not yet uploaded','{4,5,6}'::int[]),
('CZ-RULE-DEM-001','A15','One tenant carries the whole pro forma','A single anchor with a long lease is the project and it can walk.','anchor_tenant.pct_of_stabilized_noi >= 30 AND anchor_tenant.lease_status != ''EXECUTED'' OR anchor_tenant.contingency_status == ''OPEN'' OR anchor_tenant.credit_rating in [''NR'',''BELOW_INVESTMENT_GRADE'']','RED','Model the project without the anchor at market rent with realistic downtime and re-leasing cost, take that debt yield and equity return to the investment committee before the next irreversible commitment, and secure a letter of credit, termination fee or parent guarantee sized to the modeled re-tenanting cost.','Space generic and re-leasable at underwritten rent with two documented backup prospects; Lease executed unconditionally with a funded letter of credit exceeding modeled downtime cost','{1,7}'::int[]),
('CZ-RULE-DEM-002','A15','Absorption behind the underwriting','The lease-up or sales curve is not tracking and the debt has a date on it.','actual.units_leased_or_sold_to_date / forecast.units_leased_or_sold_to_date <= 0.75 AND today >= marketing.launch_date + 90 OR actual.achieved_rent < proforma.rent * 0.95','RED if debt.days_to_maturity_or_test <= 365 else YELLOW','Reprice or re-mix remaining inventory this cycle with a written concession budget and a revised absorption curve, re-test the exit cap rate and hold period against it, and take the revised curve to the lender before the coverage test date rather than after.','Slow start reflects a deliberate rent hold supported by documented traffic and conversion data; Measurement window sits in a seasonal trough evidenced in comparable lease-ups','{1,7}'::int[]),
('CZ-RULE-DEM-003','A15','Executed lease obligations not carried in budget or schedule','The deal was signed and the landlord work it promised was never funded or sequenced.','lease.status == ''EXECUTED'' AND ti_allowance.in_budget == false OR landlord_work.in_schedule == false OR lease.cotenancy_clause == true AND cotenancy.threshold_status != ''MET''','RED','Reconcile every executed lease''s landlord work exhibit, delivery condition and delivery date into the construction budget and schedule, and quantify co-tenancy and rent abatement exposure at the delivery date so it is priced rather than discovered.','TI allowance funded through a separate committed facility outside the construction budget; Co-tenancy measured at a later date and signed leases plus LOIs already clear the threshold','{1,7}'::int[])
) AS v(rule_id,aspect_id,name,description,conditions,severity_floor,action,fpc,stages) ON CONFLICT (rule_id) DO UPDATE SET aspect_id=EXCLUDED.aspect_id,name=EXCLUDED.name,description=EXCLUDED.description,conditions=EXCLUDED.conditions,severity_floor=EXCLUDED.severity_floor,action=EXCLUDED.action,false_positive_checks=EXCLUDED.false_positive_checks,stages=EXCLUDED.stages,active=true;